env:
  num_node: 2
  node_ips: #the first item in the ip list is the master ip, pls make sure that the ip doesn't contain space in the end
  #  - IP1
  #  - IP2
  tmp_path: <path-to-work-dir-on-localdisk>/ml_tmp
  data_path: <path-to-work-dir-on-localdisk>/data
  config_path: <path-to-work-dir-on-localdisk>/credit-card-fraud-detection/configs/distributed

data_preprocess:
  input_data_path: raw_data
  input_data_format: csv
  output_data_path: edge_data
  output_data_format: csv
  dp_config_file: data-preprocessing.yaml
  dp_framework: pandas
